sudo: required
services:
  - docker

before_install: 
  - docker build -t motpansergiu/docker-react -f Dockerfile.dev .

script: 
 - docker run -e CI=true motpansergiu/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "eu-central-1"
 app: "docker-react"
 env: "Docker-react-env"
 bucket_name: "elasticbeanstalk-eu-central-1-578452386702"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"

#docker-compose -f docker-compose-dev.yml up
# docker-compose -f docker-compose-dev.yml up --build
# docker-compose -f docker-compose-dev.yml down